package:
  name: primacy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  #git_url: https://github.com/FofanovLab/Primacy
  path: .
build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - primacy = primacy.main:gui

  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - python {{ python }}
    - setuptools
  run:   # channels: bioconda
    - python {{ python }}
    - click
    - biopython
    - numpy
    - pandas
    - blast # [not win]

test:
  imports:
    - primacy
  commands:
    - primacy --help
    - primacy primer-collection --help
    - primacy primer-score --help
    - primacy set-optimization --help  

about:
  home: https://github.com/FofanovLab/Primacy
  license: MIT
  license_file: LICENSE

extra:
  maintainers:
   - Tara Furstenau
