package:
  name: primacy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/FofanovLab/Primacy

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - primacy = primacy.main:gui
    - primacy_cli = primacy.main:main
  script: "{{ PYTHON }} -m pip install . -v"

requirements:
  build:
    - python>=3.6
  host:
    - python>=3.6
    - pip
  run:   # channels: bioconda
    - python>=3.6
    - click
    - biopython
    - numpy
    - pandas
    - blast # [not win]

test:
  imports:
    - primacy
  commands:
    - primacy --help
    - primacy primer-collection --help
    - primacy primer-score --help
  

about:
  home: https://github.com/FofanovLab/Primacy
  license: MIT
  license_file: LICENSE

extra:
  maintainers:
   - Tara Furstenau
