package:
  name: primacy
  version: version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/FofanovLab/Primacy

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - primacy_gui = primacy.main:gui
    - primacy = primacy.main:main
  script: "{{ PYTHON }} -m pip install . -v"

requirements:
  build:
    - python
  host:
    - python
    - pip
  run: # channels: bioconda
    - python
    - click
    - biopython
    - numpy
    - pandas
    - blast # [not win]

test:
  imports:
    - primacy

about:
  home: https://github.com/FofanovLab/Primacy
  license: MIT
  license_file: LICENSE